/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: /home/chenzk/BaseLib/BaseLib/libvideo/libvideo.i

package libvideo

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef void* swig_type_2;
typedef void* swig_type_3;
typedef void* swig_type_4;
typedef void* swig_type_5;
typedef void* swig_type_6;
typedef void* swig_type_7;
typedef void* swig_type_8;
typedef void* swig_type_9;
typedef void* swig_type_10;
typedef void* swig_type_11;
typedef void* swig_type_12;
typedef void* swig_type_13;
typedef void* swig_type_14;
typedef void* swig_type_15;
typedef void* swig_type_16;
typedef void* swig_type_17;
typedef void* swig_type_18;
typedef void* swig_type_19;
extern void _wrap_Swig_free_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_libvideo_e6881c35160e2f8e(swig_intgo arg1);
extern swig_intgo _wrap_NALU_TYPE_UNDEFINE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_SLICE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_DPA_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_DPB_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_DPC_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_IDR_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_SEI_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_SPS_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_PPS_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_AUD_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_EOSEQ_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_EOSTREAM_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_NALU_TYPE_FILL_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_FRAME_TYPE_INVALID_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_FRAME_TYPE_IDR_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_FRAME_TYPE_I_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_FRAME_TYPE_P_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_FRAME_TYPE_SKIP_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_FRAME_TYPE_I_P_MIXED_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_FRAME_TYPE_B_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_VIDEO_MIX_FULL_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_VIDEO_MIX_TWO_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_VIDEO_MIX_THREE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_VIDEO_MIX_FOUR_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_VIDEO_MIX_SIX_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_VIDEO_MIX_EIGHT_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_VIDEO_MIX_NINE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_VIDEO_MIX_THIRTEEN_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_VIDEO_MIX_SIXTEEN_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_VIDEO_MIX_TWENTY_FIVE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_VIDEO_MIX_MAX_libvideo_e6881c35160e2f8e(void);
extern void _wrap_H264_NAL_DATA_used_flag_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_H264_NAL_DATA_used_flag_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_NAL_DATA_nal_type_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_H264_NAL_DATA_nal_type_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_NAL_DATA_frame_type_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_H264_NAL_DATA_frame_type_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_NAL_DATA_timestamp_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_H264_NAL_DATA_timestamp_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_NAL_DATA_data_size_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_H264_NAL_DATA_data_size_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_NAL_DATA_data_buf_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_H264_NAL_DATA_data_buf_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_NAL_DATA_frame_end_flg_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_H264_NAL_DATA_frame_end_flg_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new_H264_NAL_DATA_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete_H264_NAL_DATA_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_RTP_PACKET_used_flag_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_H264_RTP_PACKET_used_flag_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_RTP_PACKET_seq_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_H264_RTP_PACKET_seq_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_RTP_PACKET_data_size_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_H264_RTP_PACKET_data_size_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_RTP_PACKET_data_buf_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_H264_RTP_PACKET_data_buf_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new_H264_RTP_PACKET_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete_H264_RTP_PACKET_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern swig_intgo _wrap_PICTURE_TYPE_NONE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_PICTURE_TYPE_I_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_PICTURE_TYPE_P_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_PICTURE_TYPE_B_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_PICTURE_TYPE_S_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_PICTURE_TYPE_SI_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_PICTURE_TYPE_SP_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_PICTURE_TYPE_BI_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_PIC_FMT_NONE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_PIC_FMT_YUV_I420_libvideo_e6881c35160e2f8e(void);
extern void _wrap_FRAME_PIC_DATA_pic_format_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_FRAME_PIC_DATA_pic_format_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_FRAME_PIC_DATA_pic_type_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_FRAME_PIC_DATA_pic_type_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_FRAME_PIC_DATA_timestamp_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FRAME_PIC_DATA_timestamp_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_FRAME_PIC_DATA_key_frame_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FRAME_PIC_DATA_key_frame_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_FRAME_PIC_DATA_quality_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FRAME_PIC_DATA_quality_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_FRAME_PIC_DATA_width_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FRAME_PIC_DATA_width_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_FRAME_PIC_DATA_height_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FRAME_PIC_DATA_height_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_FRAME_PIC_DATA__alloc_flg_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FRAME_PIC_DATA__alloc_flg_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_FRAME_PIC_DATA_data_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FRAME_PIC_DATA_data_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_FRAME_PIC_DATA_linesize_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FRAME_PIC_DATA_linesize_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new_FRAME_PIC_DATA_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete_FRAME_PIC_DATA_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_libv_init_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2, swig_type_1 arg3, swig_intgo arg4);
extern uintptr_t _wrap_libv_get_version_libvideo_e6881c35160e2f8e(void);
extern uintptr_t _wrap_libv_alloc_frame_pic_libvideo_e6881c35160e2f8e(swig_intgo arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_libv_copy_new_frame_pic_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_libv_free_frame_pic_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern swig_intgo _wrap_libv_get_pic_fmt_by_ffm_fmt_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_libv_get_ffm_fmt_by_pic_fmt_libvideo_e6881c35160e2f8e(swig_intgo arg1);
extern void _wrap_VIDEO_SUB_INFO_width_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_VIDEO_SUB_INFO_width_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_VIDEO_SUB_INFO_height_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_VIDEO_SUB_INFO_height_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_VIDEO_SUB_INFO_left_width_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_VIDEO_SUB_INFO_left_width_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_VIDEO_SUB_INFO_above_height_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_VIDEO_SUB_INFO_above_height_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_VIDEO_SUB_INFO_sws_ctx_ffm_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_VIDEO_SUB_INFO_sws_ctx_ffm_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_VIDEO_SUB_INFO_in_width_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_VIDEO_SUB_INFO_in_width_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_VIDEO_SUB_INFO_in_height_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_VIDEO_SUB_INFO_in_height_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new_VIDEO_SUB_INFO_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete_VIDEO_SUB_INFO_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_VIDEO_MIX_TH_mix_type_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_VIDEO_MIX_TH_mix_type_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_VIDEO_MIX_TH_out_width_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_VIDEO_MIX_TH_out_width_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_VIDEO_MIX_TH_out_height_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_VIDEO_MIX_TH_out_height_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_VIDEO_MIX_TH_out_pic_fmt_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_VIDEO_MIX_TH_out_pic_fmt_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_VIDEO_MIX_TH_sub_screens_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_VIDEO_MIX_TH_sub_screens_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new_VIDEO_MIX_TH_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete_VIDEO_MIX_TH_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_alloc_video_mix_th_libvideo_e6881c35160e2f8e(swig_intgo arg1, uintptr_t arg2, uintptr_t arg3, swig_intgo arg4);
extern void _wrap_free_video_mix_th_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_video_mix_pic_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern swig_intgo _wrap_PACKET_MODE_SINGLE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_PACKET_MODE_NON_INTERLEAVED_libvideo_e6881c35160e2f8e(void);
extern uintptr_t _wrap_alloc_h264_rtp_dec_th_libvideo_e6881c35160e2f8e(void);
extern void _wrap_free_h264_rtp_dec_th_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern swig_intgo _wrap_h264_dec_rtp_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3);
extern uintptr_t _wrap_h264_dec_rtp_get_nal_data_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern swig_voidp _wrap_alloc_h264_rtp_enc_th_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4, swig_intgo arg5);
extern void _wrap_free_h264_rtp_enc_th_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_h264_enc_rtp_one_nalu_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4, uintptr_t arg5);
extern uintptr_t _wrap_h264_enc_rtp_access_unit_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern uintptr_t _wrap_h264_enc_rtp_get_rtp_data_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern swig_intgo _wrap_H264_DECODER_ID_FFM_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_H264_DECODER_ID_OPENH264_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_H264_DECODER_ID_MAX_libvideo_e6881c35160e2f8e(void);
extern void _wrap___H264_DECODER_TH__id_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap___H264_DECODER_TH__id_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap___H264_DECODER_TH__private_data_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap___H264_DECODER_TH__private_data_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap___H264_DECODER_TH_decode_video_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_type_2 arg2);
extern swig_type_3 _wrap___H264_DECODER_TH_decode_video_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new___H264_DECODER_TH_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete___H264_DECODER_TH_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_DECODER_FACTORY_id_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_H264_DECODER_FACTORY_id_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_DECODER_FACTORY_init_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_type_4 arg2);
extern swig_type_5 _wrap_H264_DECODER_FACTORY_init_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_DECODER_FACTORY_release_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_type_6 arg2);
extern swig_type_7 _wrap_H264_DECODER_FACTORY_release_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new_H264_DECODER_FACTORY_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete_H264_DECODER_FACTORY_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_h264_decoder_init_libvideo_e6881c35160e2f8e(void);
extern uintptr_t _wrap_h264_decoder_register_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_alloc_decoder_by_id_libvideo_e6881c35160e2f8e(swig_intgo arg1);
extern void _wrap_free_decoder_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern swig_intgo _wrap_H264_ENCODER_ID_OPENH264_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_H264_ENCODER_ID_MAX_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_H264_SM_SINGLE_SLICE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_H264_SM_FIXEDSLCNUM_SLICE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_H264_SM_RASTER_SLICE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_H264_SM_DYN_SLICE_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_H264_SM_AUTO_SLICE_libvideo_e6881c35160e2f8e(void);
extern void _wrap_SLICE_CONFIG_max_slice_size_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_SLICE_CONFIG_max_slice_size_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_SLICE_CONFIG_slice_num_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_SLICE_CONFIG_slice_num_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_SLICE_CONFIG_slice_mb_num_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_SLICE_CONFIG_slice_mb_num_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new_SLICE_CONFIG_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete_SLICE_CONFIG_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern swig_intgo _wrap_H264_LOW_COMPLEXITY_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_H264_MEDIUM_COMPLEXITY_libvideo_e6881c35160e2f8e(void);
extern swig_intgo _wrap_H264_HIGH_COMPLEXITY_libvideo_e6881c35160e2f8e(void);
extern void _wrap_ENCODE_PARAMETER_pic_format_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_ENCODE_PARAMETER_pic_format_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_ENCODE_PARAMETER_profile_id_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ENCODE_PARAMETER_profile_id_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_ENCODE_PARAMETER_width_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ENCODE_PARAMETER_width_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_ENCODE_PARAMETER_height_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ENCODE_PARAMETER_height_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_ENCODE_PARAMETER_frame_rate_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ENCODE_PARAMETER_frame_rate_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_ENCODE_PARAMETER_multiple_thread_id_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ENCODE_PARAMETER_multiple_thread_id_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_ENCODE_PARAMETER_bitrate_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ENCODE_PARAMETER_bitrate_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_ENCODE_PARAMETER_max_bitrate_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ENCODE_PARAMETER_max_bitrate_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_ENCODE_PARAMETER_slice_mode_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_ENCODE_PARAMETER_slice_mode_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_ENCODE_PARAMETER_slice_cfg_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ENCODE_PARAMETER_slice_cfg_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_ENCODE_PARAMETER_complexity_mode_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_ENCODE_PARAMETER_complexity_mode_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new_ENCODE_PARAMETER_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete_ENCODE_PARAMETER_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_LAYER_BS_INFO_tmp_id_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_LAYER_BS_INFO_tmp_id_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_LAYER_BS_INFO_frame_type_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_LAYER_BS_INFO_frame_type_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_LAYER_BS_INFO_nal_count_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_LAYER_BS_INFO_nal_count_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_LAYER_BS_INFO_nal_data_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_LAYER_BS_INFO_nal_data_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new_LAYER_BS_INFO_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete_LAYER_BS_INFO_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap___H264_ENCODER_TH__id_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap___H264_ENCODER_TH__id_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap___H264_ENCODER_TH_param_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap___H264_ENCODER_TH_param_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap___H264_ENCODER_TH__private_data_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap___H264_ENCODER_TH__private_data_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap___H264_ENCODER_TH_encode_frame_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_type_8 arg2);
extern swig_type_9 _wrap___H264_ENCODER_TH_encode_frame_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap___H264_ENCODER_TH_encode_parameter_sets_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_type_10 arg2);
extern swig_type_11 _wrap___H264_ENCODER_TH_encode_parameter_sets_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap___H264_ENCODER_TH_force_intra_frame_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_type_12 arg2);
extern swig_type_13 _wrap___H264_ENCODER_TH_force_intra_frame_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap___H264_ENCODER_TH_reset_frame_rate_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_type_14 arg2);
extern swig_type_15 _wrap___H264_ENCODER_TH_reset_frame_rate_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new___H264_ENCODER_TH_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete___H264_ENCODER_TH_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_ENCODER_FACTORY_id_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_H264_ENCODER_FACTORY_id_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_ENCODER_FACTORY_init_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_type_16 arg2);
extern swig_type_17 _wrap_H264_ENCODER_FACTORY_init_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_H264_ENCODER_FACTORY_release_set_libvideo_e6881c35160e2f8e(uintptr_t arg1, swig_type_18 arg2);
extern swig_type_19 _wrap_H264_ENCODER_FACTORY_release_get_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_new_H264_ENCODER_FACTORY_libvideo_e6881c35160e2f8e(void);
extern void _wrap_delete_H264_ENCODER_FACTORY_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_h264_encoder_init_libvideo_e6881c35160e2f8e(void);
extern uintptr_t _wrap_h264_encoder_register_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern uintptr_t _wrap_alloc_encoder_by_id_libvideo_e6881c35160e2f8e(swig_intgo arg1, uintptr_t arg2);
extern void _wrap_free_encoder_libvideo_e6881c35160e2f8e(uintptr_t arg1);
extern void _wrap_ffm_decoder_init_libvideo_e6881c35160e2f8e(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_libvideo_e6881c35160e2f8e(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type Enum_SS___NALU_TYPE int
func _swig_getNALU_TYPE_UNDEFINE() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_UNDEFINE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_UNDEFINE Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_UNDEFINE()
func _swig_getNALU_TYPE_SLICE() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_SLICE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_SLICE Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_SLICE()
func _swig_getNALU_TYPE_DPA() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_DPA_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_DPA Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_DPA()
func _swig_getNALU_TYPE_DPB() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_DPB_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_DPB Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_DPB()
func _swig_getNALU_TYPE_DPC() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_DPC_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_DPC Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_DPC()
func _swig_getNALU_TYPE_IDR() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_IDR_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_IDR Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_IDR()
func _swig_getNALU_TYPE_SEI() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_SEI_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_SEI Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_SEI()
func _swig_getNALU_TYPE_SPS() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_SPS_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_SPS Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_SPS()
func _swig_getNALU_TYPE_PPS() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_PPS_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_PPS Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_PPS()
func _swig_getNALU_TYPE_AUD() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_AUD_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_AUD Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_AUD()
func _swig_getNALU_TYPE_EOSEQ() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_EOSEQ_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_EOSEQ Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_EOSEQ()
func _swig_getNALU_TYPE_EOSTREAM() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_EOSTREAM_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_EOSTREAM Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_EOSTREAM()
func _swig_getNALU_TYPE_FILL() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_NALU_TYPE_FILL_libvideo_e6881c35160e2f8e())
	return swig_r
}

var NALU_TYPE_FILL Enum_SS___NALU_TYPE = _swig_getNALU_TYPE_FILL()
type Enum_SS___FRAME_TYPE int
func _swig_getFRAME_TYPE_INVALID() (_swig_ret Enum_SS___FRAME_TYPE) {
	var swig_r Enum_SS___FRAME_TYPE
	swig_r = (Enum_SS___FRAME_TYPE)(C._wrap_FRAME_TYPE_INVALID_libvideo_e6881c35160e2f8e())
	return swig_r
}

var FRAME_TYPE_INVALID Enum_SS___FRAME_TYPE = _swig_getFRAME_TYPE_INVALID()
func _swig_getFRAME_TYPE_IDR() (_swig_ret Enum_SS___FRAME_TYPE) {
	var swig_r Enum_SS___FRAME_TYPE
	swig_r = (Enum_SS___FRAME_TYPE)(C._wrap_FRAME_TYPE_IDR_libvideo_e6881c35160e2f8e())
	return swig_r
}

var FRAME_TYPE_IDR Enum_SS___FRAME_TYPE = _swig_getFRAME_TYPE_IDR()
func _swig_getFRAME_TYPE_I() (_swig_ret Enum_SS___FRAME_TYPE) {
	var swig_r Enum_SS___FRAME_TYPE
	swig_r = (Enum_SS___FRAME_TYPE)(C._wrap_FRAME_TYPE_I_libvideo_e6881c35160e2f8e())
	return swig_r
}

var FRAME_TYPE_I Enum_SS___FRAME_TYPE = _swig_getFRAME_TYPE_I()
func _swig_getFRAME_TYPE_P() (_swig_ret Enum_SS___FRAME_TYPE) {
	var swig_r Enum_SS___FRAME_TYPE
	swig_r = (Enum_SS___FRAME_TYPE)(C._wrap_FRAME_TYPE_P_libvideo_e6881c35160e2f8e())
	return swig_r
}

var FRAME_TYPE_P Enum_SS___FRAME_TYPE = _swig_getFRAME_TYPE_P()
func _swig_getFRAME_TYPE_SKIP() (_swig_ret Enum_SS___FRAME_TYPE) {
	var swig_r Enum_SS___FRAME_TYPE
	swig_r = (Enum_SS___FRAME_TYPE)(C._wrap_FRAME_TYPE_SKIP_libvideo_e6881c35160e2f8e())
	return swig_r
}

var FRAME_TYPE_SKIP Enum_SS___FRAME_TYPE = _swig_getFRAME_TYPE_SKIP()
func _swig_getFRAME_TYPE_I_P_MIXED() (_swig_ret Enum_SS___FRAME_TYPE) {
	var swig_r Enum_SS___FRAME_TYPE
	swig_r = (Enum_SS___FRAME_TYPE)(C._wrap_FRAME_TYPE_I_P_MIXED_libvideo_e6881c35160e2f8e())
	return swig_r
}

var FRAME_TYPE_I_P_MIXED Enum_SS___FRAME_TYPE = _swig_getFRAME_TYPE_I_P_MIXED()
func _swig_getFRAME_TYPE_B() (_swig_ret Enum_SS___FRAME_TYPE) {
	var swig_r Enum_SS___FRAME_TYPE
	swig_r = (Enum_SS___FRAME_TYPE)(C._wrap_FRAME_TYPE_B_libvideo_e6881c35160e2f8e())
	return swig_r
}

var FRAME_TYPE_B Enum_SS___FRAME_TYPE = _swig_getFRAME_TYPE_B()
type Enum_SS___VIDEO_MIX_TYPE int
func _swig_getVIDEO_MIX_FULL() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_FULL_libvideo_e6881c35160e2f8e())
	return swig_r
}

var VIDEO_MIX_FULL Enum_SS___VIDEO_MIX_TYPE = _swig_getVIDEO_MIX_FULL()
func _swig_getVIDEO_MIX_TWO() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_TWO_libvideo_e6881c35160e2f8e())
	return swig_r
}

var VIDEO_MIX_TWO Enum_SS___VIDEO_MIX_TYPE = _swig_getVIDEO_MIX_TWO()
func _swig_getVIDEO_MIX_THREE() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_THREE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var VIDEO_MIX_THREE Enum_SS___VIDEO_MIX_TYPE = _swig_getVIDEO_MIX_THREE()
func _swig_getVIDEO_MIX_FOUR() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_FOUR_libvideo_e6881c35160e2f8e())
	return swig_r
}

var VIDEO_MIX_FOUR Enum_SS___VIDEO_MIX_TYPE = _swig_getVIDEO_MIX_FOUR()
func _swig_getVIDEO_MIX_SIX() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_SIX_libvideo_e6881c35160e2f8e())
	return swig_r
}

var VIDEO_MIX_SIX Enum_SS___VIDEO_MIX_TYPE = _swig_getVIDEO_MIX_SIX()
func _swig_getVIDEO_MIX_EIGHT() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_EIGHT_libvideo_e6881c35160e2f8e())
	return swig_r
}

var VIDEO_MIX_EIGHT Enum_SS___VIDEO_MIX_TYPE = _swig_getVIDEO_MIX_EIGHT()
func _swig_getVIDEO_MIX_NINE() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_NINE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var VIDEO_MIX_NINE Enum_SS___VIDEO_MIX_TYPE = _swig_getVIDEO_MIX_NINE()
func _swig_getVIDEO_MIX_THIRTEEN() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_THIRTEEN_libvideo_e6881c35160e2f8e())
	return swig_r
}

var VIDEO_MIX_THIRTEEN Enum_SS___VIDEO_MIX_TYPE = _swig_getVIDEO_MIX_THIRTEEN()
func _swig_getVIDEO_MIX_SIXTEEN() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_SIXTEEN_libvideo_e6881c35160e2f8e())
	return swig_r
}

var VIDEO_MIX_SIXTEEN Enum_SS___VIDEO_MIX_TYPE = _swig_getVIDEO_MIX_SIXTEEN()
func _swig_getVIDEO_MIX_TWENTY_FIVE() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_TWENTY_FIVE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var VIDEO_MIX_TWENTY_FIVE Enum_SS___VIDEO_MIX_TYPE = _swig_getVIDEO_MIX_TWENTY_FIVE()
func _swig_getVIDEO_MIX_MAX() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_MAX_libvideo_e6881c35160e2f8e())
	return swig_r
}

var VIDEO_MIX_MAX Enum_SS___VIDEO_MIX_TYPE = _swig_getVIDEO_MIX_MAX()
type SwigcptrH264_NAL_DATA uintptr

func (p SwigcptrH264_NAL_DATA) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrH264_NAL_DATA) SwigIsH264_NAL_DATA() {
}

func (arg1 SwigcptrH264_NAL_DATA) SetUsed_flag(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_H264_NAL_DATA_used_flag_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrH264_NAL_DATA) GetUsed_flag() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_H264_NAL_DATA_used_flag_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrH264_NAL_DATA) SetNal_type(arg2 Enum_SS___NALU_TYPE) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_H264_NAL_DATA_nal_type_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrH264_NAL_DATA) GetNal_type() (_swig_ret Enum_SS___NALU_TYPE) {
	var swig_r Enum_SS___NALU_TYPE
	_swig_i_0 := arg1
	swig_r = (Enum_SS___NALU_TYPE)(C._wrap_H264_NAL_DATA_nal_type_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrH264_NAL_DATA) SetFrame_type(arg2 Enum_SS___FRAME_TYPE) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_H264_NAL_DATA_frame_type_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrH264_NAL_DATA) GetFrame_type() (_swig_ret Enum_SS___FRAME_TYPE) {
	var swig_r Enum_SS___FRAME_TYPE
	_swig_i_0 := arg1
	swig_r = (Enum_SS___FRAME_TYPE)(C._wrap_H264_NAL_DATA_frame_type_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrH264_NAL_DATA) SetTimestamp(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_H264_NAL_DATA_timestamp_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrH264_NAL_DATA) GetTimestamp() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_H264_NAL_DATA_timestamp_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrH264_NAL_DATA) SetData_size(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_H264_NAL_DATA_data_size_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrH264_NAL_DATA) GetData_size() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_H264_NAL_DATA_data_size_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrH264_NAL_DATA) SetData_buf(arg2 Uint8_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_H264_NAL_DATA_data_buf_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrH264_NAL_DATA) GetData_buf() (_swig_ret Uint8_t) {
	var swig_r Uint8_t
	_swig_i_0 := arg1
	swig_r = (Uint8_t)(SwigcptrUint8_t(C._wrap_H264_NAL_DATA_data_buf_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrH264_NAL_DATA) SetFrame_end_flg(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_H264_NAL_DATA_frame_end_flg_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrH264_NAL_DATA) GetFrame_end_flg() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_H264_NAL_DATA_frame_end_flg_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewH264_NAL_DATA() (_swig_ret H264_NAL_DATA) {
	var swig_r H264_NAL_DATA
	swig_r = (H264_NAL_DATA)(SwigcptrH264_NAL_DATA(C._wrap_new_H264_NAL_DATA_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteH264_NAL_DATA(arg1 H264_NAL_DATA) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_H264_NAL_DATA_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type H264_NAL_DATA interface {
	Swigcptr() uintptr
	SwigIsH264_NAL_DATA()
	SetUsed_flag(arg2 Uint32_t)
	GetUsed_flag() (_swig_ret Uint32_t)
	SetNal_type(arg2 Enum_SS___NALU_TYPE)
	GetNal_type() (_swig_ret Enum_SS___NALU_TYPE)
	SetFrame_type(arg2 Enum_SS___FRAME_TYPE)
	GetFrame_type() (_swig_ret Enum_SS___FRAME_TYPE)
	SetTimestamp(arg2 Uint32_t)
	GetTimestamp() (_swig_ret Uint32_t)
	SetData_size(arg2 Uint32_t)
	GetData_size() (_swig_ret Uint32_t)
	SetData_buf(arg2 Uint8_t)
	GetData_buf() (_swig_ret Uint8_t)
	SetFrame_end_flg(arg2 Uint32_t)
	GetFrame_end_flg() (_swig_ret Uint32_t)
}

type SwigcptrH264_RTP_PACKET uintptr

func (p SwigcptrH264_RTP_PACKET) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrH264_RTP_PACKET) SwigIsH264_RTP_PACKET() {
}

func (arg1 SwigcptrH264_RTP_PACKET) SetUsed_flag(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_H264_RTP_PACKET_used_flag_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrH264_RTP_PACKET) GetUsed_flag() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_H264_RTP_PACKET_used_flag_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrH264_RTP_PACKET) SetSeq(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_H264_RTP_PACKET_seq_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrH264_RTP_PACKET) GetSeq() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_H264_RTP_PACKET_seq_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrH264_RTP_PACKET) SetData_size(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_H264_RTP_PACKET_data_size_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrH264_RTP_PACKET) GetData_size() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_H264_RTP_PACKET_data_size_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrH264_RTP_PACKET) SetData_buf(arg2 Uint8_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_H264_RTP_PACKET_data_buf_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrH264_RTP_PACKET) GetData_buf() (_swig_ret Uint8_t) {
	var swig_r Uint8_t
	_swig_i_0 := arg1
	swig_r = (Uint8_t)(SwigcptrUint8_t(C._wrap_H264_RTP_PACKET_data_buf_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewH264_RTP_PACKET() (_swig_ret H264_RTP_PACKET) {
	var swig_r H264_RTP_PACKET
	swig_r = (H264_RTP_PACKET)(SwigcptrH264_RTP_PACKET(C._wrap_new_H264_RTP_PACKET_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteH264_RTP_PACKET(arg1 H264_RTP_PACKET) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_H264_RTP_PACKET_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type H264_RTP_PACKET interface {
	Swigcptr() uintptr
	SwigIsH264_RTP_PACKET()
	SetUsed_flag(arg2 Uint32_t)
	GetUsed_flag() (_swig_ret Uint32_t)
	SetSeq(arg2 Uint32_t)
	GetSeq() (_swig_ret Uint32_t)
	SetData_size(arg2 Uint32_t)
	GetData_size() (_swig_ret Uint32_t)
	SetData_buf(arg2 Uint8_t)
	GetData_buf() (_swig_ret Uint8_t)
}

type Enum_SS___PICTURE_TYPE int
func _swig_getPICTURE_TYPE_NONE() (_swig_ret Enum_SS___PICTURE_TYPE) {
	var swig_r Enum_SS___PICTURE_TYPE
	swig_r = (Enum_SS___PICTURE_TYPE)(C._wrap_PICTURE_TYPE_NONE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PICTURE_TYPE_NONE Enum_SS___PICTURE_TYPE = _swig_getPICTURE_TYPE_NONE()
func _swig_getPICTURE_TYPE_I() (_swig_ret Enum_SS___PICTURE_TYPE) {
	var swig_r Enum_SS___PICTURE_TYPE
	swig_r = (Enum_SS___PICTURE_TYPE)(C._wrap_PICTURE_TYPE_I_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PICTURE_TYPE_I Enum_SS___PICTURE_TYPE = _swig_getPICTURE_TYPE_I()
func _swig_getPICTURE_TYPE_P() (_swig_ret Enum_SS___PICTURE_TYPE) {
	var swig_r Enum_SS___PICTURE_TYPE
	swig_r = (Enum_SS___PICTURE_TYPE)(C._wrap_PICTURE_TYPE_P_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PICTURE_TYPE_P Enum_SS___PICTURE_TYPE = _swig_getPICTURE_TYPE_P()
func _swig_getPICTURE_TYPE_B() (_swig_ret Enum_SS___PICTURE_TYPE) {
	var swig_r Enum_SS___PICTURE_TYPE
	swig_r = (Enum_SS___PICTURE_TYPE)(C._wrap_PICTURE_TYPE_B_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PICTURE_TYPE_B Enum_SS___PICTURE_TYPE = _swig_getPICTURE_TYPE_B()
func _swig_getPICTURE_TYPE_S() (_swig_ret Enum_SS___PICTURE_TYPE) {
	var swig_r Enum_SS___PICTURE_TYPE
	swig_r = (Enum_SS___PICTURE_TYPE)(C._wrap_PICTURE_TYPE_S_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PICTURE_TYPE_S Enum_SS___PICTURE_TYPE = _swig_getPICTURE_TYPE_S()
func _swig_getPICTURE_TYPE_SI() (_swig_ret Enum_SS___PICTURE_TYPE) {
	var swig_r Enum_SS___PICTURE_TYPE
	swig_r = (Enum_SS___PICTURE_TYPE)(C._wrap_PICTURE_TYPE_SI_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PICTURE_TYPE_SI Enum_SS___PICTURE_TYPE = _swig_getPICTURE_TYPE_SI()
func _swig_getPICTURE_TYPE_SP() (_swig_ret Enum_SS___PICTURE_TYPE) {
	var swig_r Enum_SS___PICTURE_TYPE
	swig_r = (Enum_SS___PICTURE_TYPE)(C._wrap_PICTURE_TYPE_SP_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PICTURE_TYPE_SP Enum_SS___PICTURE_TYPE = _swig_getPICTURE_TYPE_SP()
func _swig_getPICTURE_TYPE_BI() (_swig_ret Enum_SS___PICTURE_TYPE) {
	var swig_r Enum_SS___PICTURE_TYPE
	swig_r = (Enum_SS___PICTURE_TYPE)(C._wrap_PICTURE_TYPE_BI_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PICTURE_TYPE_BI Enum_SS___PICTURE_TYPE = _swig_getPICTURE_TYPE_BI()
type Enum_SS___PICTURE_FORMAT int
func _swig_getPIC_FMT_NONE() (_swig_ret Enum_SS___PICTURE_FORMAT) {
	var swig_r Enum_SS___PICTURE_FORMAT
	swig_r = (Enum_SS___PICTURE_FORMAT)(C._wrap_PIC_FMT_NONE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PIC_FMT_NONE Enum_SS___PICTURE_FORMAT = _swig_getPIC_FMT_NONE()
func _swig_getPIC_FMT_YUV_I420() (_swig_ret Enum_SS___PICTURE_FORMAT) {
	var swig_r Enum_SS___PICTURE_FORMAT
	swig_r = (Enum_SS___PICTURE_FORMAT)(C._wrap_PIC_FMT_YUV_I420_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PIC_FMT_YUV_I420 Enum_SS___PICTURE_FORMAT = _swig_getPIC_FMT_YUV_I420()
const LIBV_NUM_DATA_POINTERS int = 8
type SwigcptrFRAME_PIC_DATA uintptr

func (p SwigcptrFRAME_PIC_DATA) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFRAME_PIC_DATA) SwigIsFRAME_PIC_DATA() {
}

func (arg1 SwigcptrFRAME_PIC_DATA) SetPic_format(arg2 Enum_SS___PICTURE_FORMAT) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_FRAME_PIC_DATA_pic_format_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrFRAME_PIC_DATA) GetPic_format() (_swig_ret Enum_SS___PICTURE_FORMAT) {
	var swig_r Enum_SS___PICTURE_FORMAT
	_swig_i_0 := arg1
	swig_r = (Enum_SS___PICTURE_FORMAT)(C._wrap_FRAME_PIC_DATA_pic_format_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrFRAME_PIC_DATA) SetPic_type(arg2 Enum_SS___PICTURE_TYPE) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_FRAME_PIC_DATA_pic_type_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrFRAME_PIC_DATA) GetPic_type() (_swig_ret Enum_SS___PICTURE_TYPE) {
	var swig_r Enum_SS___PICTURE_TYPE
	_swig_i_0 := arg1
	swig_r = (Enum_SS___PICTURE_TYPE)(C._wrap_FRAME_PIC_DATA_pic_type_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrFRAME_PIC_DATA) SetTimestamp(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_FRAME_PIC_DATA_timestamp_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFRAME_PIC_DATA) GetTimestamp() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_FRAME_PIC_DATA_timestamp_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFRAME_PIC_DATA) SetKey_frame(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_FRAME_PIC_DATA_key_frame_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFRAME_PIC_DATA) GetKey_frame() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_FRAME_PIC_DATA_key_frame_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFRAME_PIC_DATA) SetQuality(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_FRAME_PIC_DATA_quality_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFRAME_PIC_DATA) GetQuality() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_FRAME_PIC_DATA_quality_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFRAME_PIC_DATA) SetWidth(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_FRAME_PIC_DATA_width_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFRAME_PIC_DATA) GetWidth() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_FRAME_PIC_DATA_width_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFRAME_PIC_DATA) SetHeight(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_FRAME_PIC_DATA_height_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFRAME_PIC_DATA) GetHeight() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_FRAME_PIC_DATA_height_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFRAME_PIC_DATA) SetX_alloc_flg(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_FRAME_PIC_DATA__alloc_flg_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFRAME_PIC_DATA) GetX_alloc_flg() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_FRAME_PIC_DATA__alloc_flg_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFRAME_PIC_DATA) SetData(arg2 Uint8_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_FRAME_PIC_DATA_data_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFRAME_PIC_DATA) GetData() (_swig_ret Uint8_t) {
	var swig_r Uint8_t
	_swig_i_0 := arg1
	swig_r = (Uint8_t)(SwigcptrUint8_t(C._wrap_FRAME_PIC_DATA_data_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFRAME_PIC_DATA) SetLinesize(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_FRAME_PIC_DATA_linesize_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFRAME_PIC_DATA) GetLinesize() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_FRAME_PIC_DATA_linesize_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewFRAME_PIC_DATA() (_swig_ret FRAME_PIC_DATA) {
	var swig_r FRAME_PIC_DATA
	swig_r = (FRAME_PIC_DATA)(SwigcptrFRAME_PIC_DATA(C._wrap_new_FRAME_PIC_DATA_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteFRAME_PIC_DATA(arg1 FRAME_PIC_DATA) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_FRAME_PIC_DATA_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type FRAME_PIC_DATA interface {
	Swigcptr() uintptr
	SwigIsFRAME_PIC_DATA()
	SetPic_format(arg2 Enum_SS___PICTURE_FORMAT)
	GetPic_format() (_swig_ret Enum_SS___PICTURE_FORMAT)
	SetPic_type(arg2 Enum_SS___PICTURE_TYPE)
	GetPic_type() (_swig_ret Enum_SS___PICTURE_TYPE)
	SetTimestamp(arg2 Uint32_t)
	GetTimestamp() (_swig_ret Uint32_t)
	SetKey_frame(arg2 Int32_t)
	GetKey_frame() (_swig_ret Int32_t)
	SetQuality(arg2 Int32_t)
	GetQuality() (_swig_ret Int32_t)
	SetWidth(arg2 Int32_t)
	GetWidth() (_swig_ret Int32_t)
	SetHeight(arg2 Int32_t)
	GetHeight() (_swig_ret Int32_t)
	SetX_alloc_flg(arg2 Int32_t)
	GetX_alloc_flg() (_swig_ret Int32_t)
	SetData(arg2 Uint8_t)
	GetData() (_swig_ret Uint8_t)
	SetLinesize(arg2 Int32_t)
	GetLinesize() (_swig_ret Int32_t)
}

func Libv_init(arg1 LIBV_LOG_FUN, arg2 LIBV_LOG_LEVEL_E, arg3 string, arg4 int) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libv_init_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func Libv_get_version() (_swig_ret Uint8_t) {
	var swig_r Uint8_t
	swig_r = (Uint8_t)(SwigcptrUint8_t(C._wrap_libv_get_version_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func Libv_alloc_frame_pic(arg1 Enum_SS___PICTURE_FORMAT, arg2 Int32_t, arg3 Int32_t) (_swig_ret FRAME_PIC_DATA) {
	var swig_r FRAME_PIC_DATA
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (FRAME_PIC_DATA)(SwigcptrFRAME_PIC_DATA(C._wrap_libv_alloc_frame_pic_libvideo_e6881c35160e2f8e(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func Libv_copy_new_frame_pic(arg1 FRAME_PIC_DATA) (_swig_ret FRAME_PIC_DATA) {
	var swig_r FRAME_PIC_DATA
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (FRAME_PIC_DATA)(SwigcptrFRAME_PIC_DATA(C._wrap_libv_copy_new_frame_pic_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Libv_free_frame_pic(arg1 FRAME_PIC_DATA) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_libv_free_frame_pic_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

func Libv_get_pic_fmt_by_ffm_fmt(arg1 Int32_t) (_swig_ret Enum_SS___PICTURE_FORMAT) {
	var swig_r Enum_SS___PICTURE_FORMAT
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Enum_SS___PICTURE_FORMAT)(C._wrap_libv_get_pic_fmt_by_ffm_fmt_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Libv_get_ffm_fmt_by_pic_fmt(arg1 Enum_SS___PICTURE_FORMAT) (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_libv_get_ffm_fmt_by_pic_fmt_libvideo_e6881c35160e2f8e(C.swig_intgo(_swig_i_0))))
	return swig_r
}

const MAX_MIX_SCREEN_COUNT int = 25
const MAX_MIX_SCREEN_TOKEN_COUNT int = 5
type SwigcptrVIDEO_SUB_INFO uintptr

func (p SwigcptrVIDEO_SUB_INFO) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVIDEO_SUB_INFO) SwigIsVIDEO_SUB_INFO() {
}

func (arg1 SwigcptrVIDEO_SUB_INFO) SetWidth(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_VIDEO_SUB_INFO_width_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_SUB_INFO) GetWidth() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_VIDEO_SUB_INFO_width_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVIDEO_SUB_INFO) SetHeight(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_VIDEO_SUB_INFO_height_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_SUB_INFO) GetHeight() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_VIDEO_SUB_INFO_height_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVIDEO_SUB_INFO) SetLeft_width(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_VIDEO_SUB_INFO_left_width_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_SUB_INFO) GetLeft_width() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_VIDEO_SUB_INFO_left_width_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVIDEO_SUB_INFO) SetAbove_height(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_VIDEO_SUB_INFO_above_height_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_SUB_INFO) GetAbove_height() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_VIDEO_SUB_INFO_above_height_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVIDEO_SUB_INFO) SetSws_ctx_ffm(arg2 Struct_SS_SwsContext) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_VIDEO_SUB_INFO_sws_ctx_ffm_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_SUB_INFO) GetSws_ctx_ffm() (_swig_ret Struct_SS_SwsContext) {
	var swig_r Struct_SS_SwsContext
	_swig_i_0 := arg1
	swig_r = (Struct_SS_SwsContext)(SwigcptrStruct_SS_SwsContext(C._wrap_VIDEO_SUB_INFO_sws_ctx_ffm_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVIDEO_SUB_INFO) SetIn_width(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_VIDEO_SUB_INFO_in_width_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_SUB_INFO) GetIn_width() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_VIDEO_SUB_INFO_in_width_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVIDEO_SUB_INFO) SetIn_height(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_VIDEO_SUB_INFO_in_height_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_SUB_INFO) GetIn_height() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_VIDEO_SUB_INFO_in_height_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewVIDEO_SUB_INFO() (_swig_ret VIDEO_SUB_INFO) {
	var swig_r VIDEO_SUB_INFO
	swig_r = (VIDEO_SUB_INFO)(SwigcptrVIDEO_SUB_INFO(C._wrap_new_VIDEO_SUB_INFO_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteVIDEO_SUB_INFO(arg1 VIDEO_SUB_INFO) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_VIDEO_SUB_INFO_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type VIDEO_SUB_INFO interface {
	Swigcptr() uintptr
	SwigIsVIDEO_SUB_INFO()
	SetWidth(arg2 Int32_t)
	GetWidth() (_swig_ret Int32_t)
	SetHeight(arg2 Int32_t)
	GetHeight() (_swig_ret Int32_t)
	SetLeft_width(arg2 Int32_t)
	GetLeft_width() (_swig_ret Int32_t)
	SetAbove_height(arg2 Int32_t)
	GetAbove_height() (_swig_ret Int32_t)
	SetSws_ctx_ffm(arg2 Struct_SS_SwsContext)
	GetSws_ctx_ffm() (_swig_ret Struct_SS_SwsContext)
	SetIn_width(arg2 Int32_t)
	GetIn_width() (_swig_ret Int32_t)
	SetIn_height(arg2 Int32_t)
	GetIn_height() (_swig_ret Int32_t)
}

type SwigcptrVIDEO_MIX_TH uintptr

func (p SwigcptrVIDEO_MIX_TH) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrVIDEO_MIX_TH) SwigIsVIDEO_MIX_TH() {
}

func (arg1 SwigcptrVIDEO_MIX_TH) SetMix_type(arg2 Enum_SS___VIDEO_MIX_TYPE) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_VIDEO_MIX_TH_mix_type_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_MIX_TH) GetMix_type() (_swig_ret Enum_SS___VIDEO_MIX_TYPE) {
	var swig_r Enum_SS___VIDEO_MIX_TYPE
	_swig_i_0 := arg1
	swig_r = (Enum_SS___VIDEO_MIX_TYPE)(C._wrap_VIDEO_MIX_TH_mix_type_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVIDEO_MIX_TH) SetOut_width(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_VIDEO_MIX_TH_out_width_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_MIX_TH) GetOut_width() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_VIDEO_MIX_TH_out_width_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVIDEO_MIX_TH) SetOut_height(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_VIDEO_MIX_TH_out_height_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_MIX_TH) GetOut_height() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_VIDEO_MIX_TH_out_height_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrVIDEO_MIX_TH) SetOut_pic_fmt(arg2 Enum_SS___PICTURE_FORMAT) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_VIDEO_MIX_TH_out_pic_fmt_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_MIX_TH) GetOut_pic_fmt() (_swig_ret Enum_SS___PICTURE_FORMAT) {
	var swig_r Enum_SS___PICTURE_FORMAT
	_swig_i_0 := arg1
	swig_r = (Enum_SS___PICTURE_FORMAT)(C._wrap_VIDEO_MIX_TH_out_pic_fmt_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrVIDEO_MIX_TH) SetSub_screens(arg2 VIDEO_SUB_INFO) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_VIDEO_MIX_TH_sub_screens_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrVIDEO_MIX_TH) GetSub_screens() (_swig_ret VIDEO_SUB_INFO) {
	var swig_r VIDEO_SUB_INFO
	_swig_i_0 := arg1
	swig_r = (VIDEO_SUB_INFO)(SwigcptrVIDEO_SUB_INFO(C._wrap_VIDEO_MIX_TH_sub_screens_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewVIDEO_MIX_TH() (_swig_ret VIDEO_MIX_TH) {
	var swig_r VIDEO_MIX_TH
	swig_r = (VIDEO_MIX_TH)(SwigcptrVIDEO_MIX_TH(C._wrap_new_VIDEO_MIX_TH_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteVIDEO_MIX_TH(arg1 VIDEO_MIX_TH) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_VIDEO_MIX_TH_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type VIDEO_MIX_TH interface {
	Swigcptr() uintptr
	SwigIsVIDEO_MIX_TH()
	SetMix_type(arg2 Enum_SS___VIDEO_MIX_TYPE)
	GetMix_type() (_swig_ret Enum_SS___VIDEO_MIX_TYPE)
	SetOut_width(arg2 Int32_t)
	GetOut_width() (_swig_ret Int32_t)
	SetOut_height(arg2 Int32_t)
	GetOut_height() (_swig_ret Int32_t)
	SetOut_pic_fmt(arg2 Enum_SS___PICTURE_FORMAT)
	GetOut_pic_fmt() (_swig_ret Enum_SS___PICTURE_FORMAT)
	SetSub_screens(arg2 VIDEO_SUB_INFO)
	GetSub_screens() (_swig_ret VIDEO_SUB_INFO)
}

func Alloc_video_mix_th(arg1 Enum_SS___VIDEO_MIX_TYPE, arg2 Int32_t, arg3 Int32_t, arg4 Enum_SS___PICTURE_FORMAT) (_swig_ret VIDEO_MIX_TH) {
	var swig_r VIDEO_MIX_TH
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	swig_r = (VIDEO_MIX_TH)(SwigcptrVIDEO_MIX_TH(C._wrap_alloc_video_mix_th_libvideo_e6881c35160e2f8e(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_intgo(_swig_i_3))))
	return swig_r
}

func Free_video_mix_th(arg1 VIDEO_MIX_TH) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_free_video_mix_th_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

func Video_mix_pic(arg1 VIDEO_MIX_TH, arg2 FRAME_PIC_DATA, arg3 Int32_t, arg4 FRAME_PIC_DATA) (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_video_mix_pic_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

type PACKET_MODE_E int
func _swig_getPACKET_MODE_SINGLE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_PACKET_MODE_SINGLE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PACKET_MODE_SINGLE int = _swig_getPACKET_MODE_SINGLE()
func _swig_getPACKET_MODE_NON_INTERLEAVED() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_PACKET_MODE_NON_INTERLEAVED_libvideo_e6881c35160e2f8e())
	return swig_r
}

var PACKET_MODE_NON_INTERLEAVED int = _swig_getPACKET_MODE_NON_INTERLEAVED()
func Alloc_h264_rtp_dec_th() (_swig_ret uintptr) {
	var swig_r uintptr
	swig_r = (uintptr)(C._wrap_alloc_h264_rtp_dec_th_libvideo_e6881c35160e2f8e())
	return swig_r
}

func Free_h264_rtp_dec_th(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_free_h264_rtp_dec_th_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

func H264_dec_rtp(arg1 uintptr, arg2 Uint8_t, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_h264_dec_rtp_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func H264_dec_rtp_get_nal_data(arg1 uintptr) (_swig_ret H264_NAL_DATA) {
	var swig_r H264_NAL_DATA
	_swig_i_0 := arg1
	swig_r = (H264_NAL_DATA)(SwigcptrH264_NAL_DATA(C._wrap_h264_dec_rtp_get_nal_data_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Alloc_h264_rtp_enc_th(arg1 Uint8_t, arg2 Uint16_t, arg3 Uint32_t, arg4 Uint32_t, arg5 PACKET_MODE_E) (_swig_ret *uintptr) {
	var swig_r *uintptr
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5
	swig_r = (*uintptr)(C._wrap_alloc_h264_rtp_enc_th_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.swig_intgo(_swig_i_4)))
	return swig_r
}

func Free_h264_rtp_enc_th(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_free_h264_rtp_enc_th_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

func H264_enc_rtp_one_nalu(arg1 uintptr, arg2 Uint8_t, arg3 Int32_t, arg4 Uint32_t, arg5 Uint32_t) (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5.Swigcptr()
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_h264_enc_rtp_one_nalu_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.uintptr_t(_swig_i_4))))
	return swig_r
}

func H264_enc_rtp_access_unit(arg1 uintptr, arg2 Uint8_t, arg3 Int32_t, arg4 Uint32_t) (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_h264_enc_rtp_access_unit_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func H264_enc_rtp_get_rtp_data(arg1 uintptr) (_swig_ret H264_RTP_PACKET) {
	var swig_r H264_RTP_PACKET
	_swig_i_0 := arg1
	swig_r = (H264_RTP_PACKET)(SwigcptrH264_RTP_PACKET(C._wrap_h264_enc_rtp_get_rtp_data_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

type Enum_SS___H264_DECODER_ID int
func _swig_getH264_DECODER_ID_FFM() (_swig_ret Enum_SS___H264_DECODER_ID) {
	var swig_r Enum_SS___H264_DECODER_ID
	swig_r = (Enum_SS___H264_DECODER_ID)(C._wrap_H264_DECODER_ID_FFM_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_DECODER_ID_FFM Enum_SS___H264_DECODER_ID = _swig_getH264_DECODER_ID_FFM()
func _swig_getH264_DECODER_ID_OPENH264() (_swig_ret Enum_SS___H264_DECODER_ID) {
	var swig_r Enum_SS___H264_DECODER_ID
	swig_r = (Enum_SS___H264_DECODER_ID)(C._wrap_H264_DECODER_ID_OPENH264_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_DECODER_ID_OPENH264 Enum_SS___H264_DECODER_ID = _swig_getH264_DECODER_ID_OPENH264()
func _swig_getH264_DECODER_ID_MAX() (_swig_ret Enum_SS___H264_DECODER_ID) {
	var swig_r Enum_SS___H264_DECODER_ID
	swig_r = (Enum_SS___H264_DECODER_ID)(C._wrap_H264_DECODER_ID_MAX_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_DECODER_ID_MAX Enum_SS___H264_DECODER_ID = _swig_getH264_DECODER_ID_MAX()
type SwigcptrX__H264_DECODER_TH uintptr

func (p SwigcptrX__H264_DECODER_TH) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrX__H264_DECODER_TH) SwigIsX__H264_DECODER_TH() {
}

func (arg1 SwigcptrX__H264_DECODER_TH) SetX_id(arg2 Enum_SS___H264_DECODER_ID) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap___H264_DECODER_TH__id_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrX__H264_DECODER_TH) GetX_id() (_swig_ret Enum_SS___H264_DECODER_ID) {
	var swig_r Enum_SS___H264_DECODER_ID
	_swig_i_0 := arg1
	swig_r = (Enum_SS___H264_DECODER_ID)(C._wrap___H264_DECODER_TH__id_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrX__H264_DECODER_TH) SetX_private_data(arg2 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap___H264_DECODER_TH__private_data_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrX__H264_DECODER_TH) GetX_private_data() (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap___H264_DECODER_TH__private_data_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrX__H264_DECODER_TH) SetDecode_video(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap___H264_DECODER_TH_decode_video_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_type_2(_swig_i_1))
}

func (arg1 SwigcptrX__H264_DECODER_TH) GetDecode_video() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap___H264_DECODER_TH_decode_video_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewX__H264_DECODER_TH() (_swig_ret X__H264_DECODER_TH) {
	var swig_r X__H264_DECODER_TH
	swig_r = (X__H264_DECODER_TH)(SwigcptrX__H264_DECODER_TH(C._wrap_new___H264_DECODER_TH_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteX__H264_DECODER_TH(arg1 X__H264_DECODER_TH) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete___H264_DECODER_TH_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type X__H264_DECODER_TH interface {
	Swigcptr() uintptr
	SwigIsX__H264_DECODER_TH()
	SetX_id(arg2 Enum_SS___H264_DECODER_ID)
	GetX_id() (_swig_ret Enum_SS___H264_DECODER_ID)
	SetX_private_data(arg2 uintptr)
	GetX_private_data() (_swig_ret uintptr)
	SetDecode_video(arg2 _swig_fnptr)
	GetDecode_video() (_swig_ret _swig_fnptr)
}

type SwigcptrH264_DECODER_FACTORY uintptr

func (p SwigcptrH264_DECODER_FACTORY) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrH264_DECODER_FACTORY) SwigIsH264_DECODER_FACTORY() {
}

func (arg1 SwigcptrH264_DECODER_FACTORY) SetId(arg2 Enum_SS___H264_DECODER_ID) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_H264_DECODER_FACTORY_id_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrH264_DECODER_FACTORY) GetId() (_swig_ret Enum_SS___H264_DECODER_ID) {
	var swig_r Enum_SS___H264_DECODER_ID
	_swig_i_0 := arg1
	swig_r = (Enum_SS___H264_DECODER_ID)(C._wrap_H264_DECODER_FACTORY_id_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrH264_DECODER_FACTORY) SetInit(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_H264_DECODER_FACTORY_init_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1))
}

func (arg1 SwigcptrH264_DECODER_FACTORY) GetInit() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_H264_DECODER_FACTORY_init_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrH264_DECODER_FACTORY) SetRelease(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_H264_DECODER_FACTORY_release_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_type_6(_swig_i_1))
}

func (arg1 SwigcptrH264_DECODER_FACTORY) GetRelease() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_H264_DECODER_FACTORY_release_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewH264_DECODER_FACTORY() (_swig_ret H264_DECODER_FACTORY) {
	var swig_r H264_DECODER_FACTORY
	swig_r = (H264_DECODER_FACTORY)(SwigcptrH264_DECODER_FACTORY(C._wrap_new_H264_DECODER_FACTORY_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteH264_DECODER_FACTORY(arg1 H264_DECODER_FACTORY) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_H264_DECODER_FACTORY_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type H264_DECODER_FACTORY interface {
	Swigcptr() uintptr
	SwigIsH264_DECODER_FACTORY()
	SetId(arg2 Enum_SS___H264_DECODER_ID)
	GetId() (_swig_ret Enum_SS___H264_DECODER_ID)
	SetInit(arg2 _swig_fnptr)
	GetInit() (_swig_ret _swig_fnptr)
	SetRelease(arg2 _swig_fnptr)
	GetRelease() (_swig_ret _swig_fnptr)
}

func H264_decoder_init() {
	C._wrap_h264_decoder_init_libvideo_e6881c35160e2f8e()
}

func H264_decoder_register(arg1 H264_DECODER_FACTORY) (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_h264_decoder_register_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Alloc_decoder_by_id(arg1 Enum_SS___H264_DECODER_ID) (_swig_ret X__H264_DECODER_TH) {
	var swig_r X__H264_DECODER_TH
	_swig_i_0 := arg1
	swig_r = (X__H264_DECODER_TH)(SwigcptrX__H264_DECODER_TH(C._wrap_alloc_decoder_by_id_libvideo_e6881c35160e2f8e(C.swig_intgo(_swig_i_0))))
	return swig_r
}

func Free_decoder(arg1 X__H264_DECODER_TH) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_free_decoder_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

const MAX_NAL_UNITS_COUNT_IN_LAYER int = 512
type Enum_SS___H264_ENCODER_ID int
func _swig_getH264_ENCODER_ID_OPENH264() (_swig_ret Enum_SS___H264_ENCODER_ID) {
	var swig_r Enum_SS___H264_ENCODER_ID
	swig_r = (Enum_SS___H264_ENCODER_ID)(C._wrap_H264_ENCODER_ID_OPENH264_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_ENCODER_ID_OPENH264 Enum_SS___H264_ENCODER_ID = _swig_getH264_ENCODER_ID_OPENH264()
func _swig_getH264_ENCODER_ID_MAX() (_swig_ret Enum_SS___H264_ENCODER_ID) {
	var swig_r Enum_SS___H264_ENCODER_ID
	swig_r = (Enum_SS___H264_ENCODER_ID)(C._wrap_H264_ENCODER_ID_MAX_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_ENCODER_ID_MAX Enum_SS___H264_ENCODER_ID = _swig_getH264_ENCODER_ID_MAX()
type H264_SLICE_MODE_E int
func _swig_getH264_SM_SINGLE_SLICE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_H264_SM_SINGLE_SLICE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_SM_SINGLE_SLICE int = _swig_getH264_SM_SINGLE_SLICE()
func _swig_getH264_SM_FIXEDSLCNUM_SLICE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_H264_SM_FIXEDSLCNUM_SLICE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_SM_FIXEDSLCNUM_SLICE int = _swig_getH264_SM_FIXEDSLCNUM_SLICE()
func _swig_getH264_SM_RASTER_SLICE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_H264_SM_RASTER_SLICE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_SM_RASTER_SLICE int = _swig_getH264_SM_RASTER_SLICE()
func _swig_getH264_SM_DYN_SLICE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_H264_SM_DYN_SLICE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_SM_DYN_SLICE int = _swig_getH264_SM_DYN_SLICE()
func _swig_getH264_SM_AUTO_SLICE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_H264_SM_AUTO_SLICE_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_SM_AUTO_SLICE int = _swig_getH264_SM_AUTO_SLICE()
type SwigcptrSLICE_CONFIG uintptr

func (p SwigcptrSLICE_CONFIG) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSLICE_CONFIG) SwigIsSLICE_CONFIG() {
}

func (arg1 SwigcptrSLICE_CONFIG) SetMax_slice_size(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_SLICE_CONFIG_max_slice_size_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrSLICE_CONFIG) GetMax_slice_size() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_SLICE_CONFIG_max_slice_size_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSLICE_CONFIG) SetSlice_num(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_SLICE_CONFIG_slice_num_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrSLICE_CONFIG) GetSlice_num() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_SLICE_CONFIG_slice_num_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSLICE_CONFIG) SetSlice_mb_num(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_SLICE_CONFIG_slice_mb_num_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrSLICE_CONFIG) GetSlice_mb_num() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_SLICE_CONFIG_slice_mb_num_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewSLICE_CONFIG() (_swig_ret SLICE_CONFIG) {
	var swig_r SLICE_CONFIG
	swig_r = (SLICE_CONFIG)(SwigcptrSLICE_CONFIG(C._wrap_new_SLICE_CONFIG_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteSLICE_CONFIG(arg1 SLICE_CONFIG) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_SLICE_CONFIG_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type SLICE_CONFIG interface {
	Swigcptr() uintptr
	SwigIsSLICE_CONFIG()
	SetMax_slice_size(arg2 Uint32_t)
	GetMax_slice_size() (_swig_ret Uint32_t)
	SetSlice_num(arg2 Uint32_t)
	GetSlice_num() (_swig_ret Uint32_t)
	SetSlice_mb_num(arg2 Uint32_t)
	GetSlice_mb_num() (_swig_ret Uint32_t)
}

type H264_ECOMPLEXITY_MODE int
func _swig_getH264_LOW_COMPLEXITY() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_H264_LOW_COMPLEXITY_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_LOW_COMPLEXITY int = _swig_getH264_LOW_COMPLEXITY()
func _swig_getH264_MEDIUM_COMPLEXITY() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_H264_MEDIUM_COMPLEXITY_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_MEDIUM_COMPLEXITY int = _swig_getH264_MEDIUM_COMPLEXITY()
func _swig_getH264_HIGH_COMPLEXITY() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_H264_HIGH_COMPLEXITY_libvideo_e6881c35160e2f8e())
	return swig_r
}

var H264_HIGH_COMPLEXITY int = _swig_getH264_HIGH_COMPLEXITY()
type SwigcptrENCODE_PARAMETER uintptr

func (p SwigcptrENCODE_PARAMETER) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrENCODE_PARAMETER) SwigIsENCODE_PARAMETER() {
}

func (arg1 SwigcptrENCODE_PARAMETER) SetPic_format(arg2 Enum_SS___PICTURE_FORMAT) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ENCODE_PARAMETER_pic_format_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrENCODE_PARAMETER) GetPic_format() (_swig_ret Enum_SS___PICTURE_FORMAT) {
	var swig_r Enum_SS___PICTURE_FORMAT
	_swig_i_0 := arg1
	swig_r = (Enum_SS___PICTURE_FORMAT)(C._wrap_ENCODE_PARAMETER_pic_format_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrENCODE_PARAMETER) SetProfile_id(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_ENCODE_PARAMETER_profile_id_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrENCODE_PARAMETER) GetProfile_id() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_ENCODE_PARAMETER_profile_id_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrENCODE_PARAMETER) SetWidth(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_ENCODE_PARAMETER_width_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrENCODE_PARAMETER) GetWidth() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_ENCODE_PARAMETER_width_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrENCODE_PARAMETER) SetHeight(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_ENCODE_PARAMETER_height_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrENCODE_PARAMETER) GetHeight() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_ENCODE_PARAMETER_height_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrENCODE_PARAMETER) SetFrame_rate(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_ENCODE_PARAMETER_frame_rate_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrENCODE_PARAMETER) GetFrame_rate() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_ENCODE_PARAMETER_frame_rate_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrENCODE_PARAMETER) SetMultiple_thread_id(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_ENCODE_PARAMETER_multiple_thread_id_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrENCODE_PARAMETER) GetMultiple_thread_id() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_ENCODE_PARAMETER_multiple_thread_id_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrENCODE_PARAMETER) SetBitrate(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_ENCODE_PARAMETER_bitrate_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrENCODE_PARAMETER) GetBitrate() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_ENCODE_PARAMETER_bitrate_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrENCODE_PARAMETER) SetMax_bitrate(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_ENCODE_PARAMETER_max_bitrate_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrENCODE_PARAMETER) GetMax_bitrate() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_ENCODE_PARAMETER_max_bitrate_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrENCODE_PARAMETER) SetSlice_mode(arg2 H264_SLICE_MODE_E) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ENCODE_PARAMETER_slice_mode_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrENCODE_PARAMETER) GetSlice_mode() (_swig_ret H264_SLICE_MODE_E) {
	var swig_r H264_SLICE_MODE_E
	_swig_i_0 := arg1
	swig_r = (H264_SLICE_MODE_E)(C._wrap_ENCODE_PARAMETER_slice_mode_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrENCODE_PARAMETER) SetSlice_cfg(arg2 SLICE_CONFIG) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_ENCODE_PARAMETER_slice_cfg_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrENCODE_PARAMETER) GetSlice_cfg() (_swig_ret SLICE_CONFIG) {
	var swig_r SLICE_CONFIG
	_swig_i_0 := arg1
	swig_r = (SLICE_CONFIG)(SwigcptrSLICE_CONFIG(C._wrap_ENCODE_PARAMETER_slice_cfg_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrENCODE_PARAMETER) SetComplexity_mode(arg2 H264_ECOMPLEXITY_MODE) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ENCODE_PARAMETER_complexity_mode_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrENCODE_PARAMETER) GetComplexity_mode() (_swig_ret H264_ECOMPLEXITY_MODE) {
	var swig_r H264_ECOMPLEXITY_MODE
	_swig_i_0 := arg1
	swig_r = (H264_ECOMPLEXITY_MODE)(C._wrap_ENCODE_PARAMETER_complexity_mode_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewENCODE_PARAMETER() (_swig_ret ENCODE_PARAMETER) {
	var swig_r ENCODE_PARAMETER
	swig_r = (ENCODE_PARAMETER)(SwigcptrENCODE_PARAMETER(C._wrap_new_ENCODE_PARAMETER_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteENCODE_PARAMETER(arg1 ENCODE_PARAMETER) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ENCODE_PARAMETER_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type ENCODE_PARAMETER interface {
	Swigcptr() uintptr
	SwigIsENCODE_PARAMETER()
	SetPic_format(arg2 Enum_SS___PICTURE_FORMAT)
	GetPic_format() (_swig_ret Enum_SS___PICTURE_FORMAT)
	SetProfile_id(arg2 Int32_t)
	GetProfile_id() (_swig_ret Int32_t)
	SetWidth(arg2 Int32_t)
	GetWidth() (_swig_ret Int32_t)
	SetHeight(arg2 Int32_t)
	GetHeight() (_swig_ret Int32_t)
	SetFrame_rate(arg2 Int32_t)
	GetFrame_rate() (_swig_ret Int32_t)
	SetMultiple_thread_id(arg2 Int32_t)
	GetMultiple_thread_id() (_swig_ret Int32_t)
	SetBitrate(arg2 Int32_t)
	GetBitrate() (_swig_ret Int32_t)
	SetMax_bitrate(arg2 Int32_t)
	GetMax_bitrate() (_swig_ret Int32_t)
	SetSlice_mode(arg2 H264_SLICE_MODE_E)
	GetSlice_mode() (_swig_ret H264_SLICE_MODE_E)
	SetSlice_cfg(arg2 SLICE_CONFIG)
	GetSlice_cfg() (_swig_ret SLICE_CONFIG)
	SetComplexity_mode(arg2 H264_ECOMPLEXITY_MODE)
	GetComplexity_mode() (_swig_ret H264_ECOMPLEXITY_MODE)
}

type SwigcptrLAYER_BS_INFO uintptr

func (p SwigcptrLAYER_BS_INFO) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrLAYER_BS_INFO) SwigIsLAYER_BS_INFO() {
}

func (arg1 SwigcptrLAYER_BS_INFO) SetTmp_id(arg2 Uint8_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_LAYER_BS_INFO_tmp_id_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrLAYER_BS_INFO) GetTmp_id() (_swig_ret Uint8_t) {
	var swig_r Uint8_t
	_swig_i_0 := arg1
	swig_r = (Uint8_t)(SwigcptrUint8_t(C._wrap_LAYER_BS_INFO_tmp_id_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrLAYER_BS_INFO) SetFrame_type(arg2 Enum_SS___FRAME_TYPE) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_LAYER_BS_INFO_frame_type_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrLAYER_BS_INFO) GetFrame_type() (_swig_ret Enum_SS___FRAME_TYPE) {
	var swig_r Enum_SS___FRAME_TYPE
	_swig_i_0 := arg1
	swig_r = (Enum_SS___FRAME_TYPE)(C._wrap_LAYER_BS_INFO_frame_type_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrLAYER_BS_INFO) SetNal_count(arg2 Int32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_LAYER_BS_INFO_nal_count_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrLAYER_BS_INFO) GetNal_count() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_LAYER_BS_INFO_nal_count_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrLAYER_BS_INFO) SetNal_data(arg2 H264_NAL_DATA) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_LAYER_BS_INFO_nal_data_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrLAYER_BS_INFO) GetNal_data() (_swig_ret H264_NAL_DATA) {
	var swig_r H264_NAL_DATA
	_swig_i_0 := arg1
	swig_r = (H264_NAL_DATA)(SwigcptrH264_NAL_DATA(C._wrap_LAYER_BS_INFO_nal_data_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewLAYER_BS_INFO() (_swig_ret LAYER_BS_INFO) {
	var swig_r LAYER_BS_INFO
	swig_r = (LAYER_BS_INFO)(SwigcptrLAYER_BS_INFO(C._wrap_new_LAYER_BS_INFO_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteLAYER_BS_INFO(arg1 LAYER_BS_INFO) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_LAYER_BS_INFO_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type LAYER_BS_INFO interface {
	Swigcptr() uintptr
	SwigIsLAYER_BS_INFO()
	SetTmp_id(arg2 Uint8_t)
	GetTmp_id() (_swig_ret Uint8_t)
	SetFrame_type(arg2 Enum_SS___FRAME_TYPE)
	GetFrame_type() (_swig_ret Enum_SS___FRAME_TYPE)
	SetNal_count(arg2 Int32_t)
	GetNal_count() (_swig_ret Int32_t)
	SetNal_data(arg2 H264_NAL_DATA)
	GetNal_data() (_swig_ret H264_NAL_DATA)
}

type SwigcptrX__H264_ENCODER_TH uintptr

func (p SwigcptrX__H264_ENCODER_TH) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrX__H264_ENCODER_TH) SwigIsX__H264_ENCODER_TH() {
}

func (arg1 SwigcptrX__H264_ENCODER_TH) SetX_id(arg2 Enum_SS___H264_ENCODER_ID) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap___H264_ENCODER_TH__id_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrX__H264_ENCODER_TH) GetX_id() (_swig_ret Enum_SS___H264_ENCODER_ID) {
	var swig_r Enum_SS___H264_ENCODER_ID
	_swig_i_0 := arg1
	swig_r = (Enum_SS___H264_ENCODER_ID)(C._wrap___H264_ENCODER_TH__id_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrX__H264_ENCODER_TH) SetParam(arg2 ENCODE_PARAMETER) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap___H264_ENCODER_TH_param_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrX__H264_ENCODER_TH) GetParam() (_swig_ret ENCODE_PARAMETER) {
	var swig_r ENCODE_PARAMETER
	_swig_i_0 := arg1
	swig_r = (ENCODE_PARAMETER)(SwigcptrENCODE_PARAMETER(C._wrap___H264_ENCODER_TH_param_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrX__H264_ENCODER_TH) SetX_private_data(arg2 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap___H264_ENCODER_TH__private_data_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrX__H264_ENCODER_TH) GetX_private_data() (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap___H264_ENCODER_TH__private_data_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrX__H264_ENCODER_TH) SetEncode_frame(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap___H264_ENCODER_TH_encode_frame_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_type_8(_swig_i_1))
}

func (arg1 SwigcptrX__H264_ENCODER_TH) GetEncode_frame() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap___H264_ENCODER_TH_encode_frame_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrX__H264_ENCODER_TH) SetEncode_parameter_sets(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap___H264_ENCODER_TH_encode_parameter_sets_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_type_10(_swig_i_1))
}

func (arg1 SwigcptrX__H264_ENCODER_TH) GetEncode_parameter_sets() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap___H264_ENCODER_TH_encode_parameter_sets_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrX__H264_ENCODER_TH) SetForce_intra_frame(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap___H264_ENCODER_TH_force_intra_frame_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_type_12(_swig_i_1))
}

func (arg1 SwigcptrX__H264_ENCODER_TH) GetForce_intra_frame() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap___H264_ENCODER_TH_force_intra_frame_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrX__H264_ENCODER_TH) SetReset_frame_rate(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap___H264_ENCODER_TH_reset_frame_rate_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_type_14(_swig_i_1))
}

func (arg1 SwigcptrX__H264_ENCODER_TH) GetReset_frame_rate() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap___H264_ENCODER_TH_reset_frame_rate_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewX__H264_ENCODER_TH() (_swig_ret X__H264_ENCODER_TH) {
	var swig_r X__H264_ENCODER_TH
	swig_r = (X__H264_ENCODER_TH)(SwigcptrX__H264_ENCODER_TH(C._wrap_new___H264_ENCODER_TH_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteX__H264_ENCODER_TH(arg1 X__H264_ENCODER_TH) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete___H264_ENCODER_TH_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type X__H264_ENCODER_TH interface {
	Swigcptr() uintptr
	SwigIsX__H264_ENCODER_TH()
	SetX_id(arg2 Enum_SS___H264_ENCODER_ID)
	GetX_id() (_swig_ret Enum_SS___H264_ENCODER_ID)
	SetParam(arg2 ENCODE_PARAMETER)
	GetParam() (_swig_ret ENCODE_PARAMETER)
	SetX_private_data(arg2 uintptr)
	GetX_private_data() (_swig_ret uintptr)
	SetEncode_frame(arg2 _swig_fnptr)
	GetEncode_frame() (_swig_ret _swig_fnptr)
	SetEncode_parameter_sets(arg2 _swig_fnptr)
	GetEncode_parameter_sets() (_swig_ret _swig_fnptr)
	SetForce_intra_frame(arg2 _swig_fnptr)
	GetForce_intra_frame() (_swig_ret _swig_fnptr)
	SetReset_frame_rate(arg2 _swig_fnptr)
	GetReset_frame_rate() (_swig_ret _swig_fnptr)
}

type SwigcptrH264_ENCODER_FACTORY uintptr

func (p SwigcptrH264_ENCODER_FACTORY) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrH264_ENCODER_FACTORY) SwigIsH264_ENCODER_FACTORY() {
}

func (arg1 SwigcptrH264_ENCODER_FACTORY) SetId(arg2 Enum_SS___H264_ENCODER_ID) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_H264_ENCODER_FACTORY_id_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrH264_ENCODER_FACTORY) GetId() (_swig_ret Enum_SS___H264_ENCODER_ID) {
	var swig_r Enum_SS___H264_ENCODER_ID
	_swig_i_0 := arg1
	swig_r = (Enum_SS___H264_ENCODER_ID)(C._wrap_H264_ENCODER_FACTORY_id_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrH264_ENCODER_FACTORY) SetInit(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_H264_ENCODER_FACTORY_init_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_type_16(_swig_i_1))
}

func (arg1 SwigcptrH264_ENCODER_FACTORY) GetInit() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_H264_ENCODER_FACTORY_init_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrH264_ENCODER_FACTORY) SetRelease(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_H264_ENCODER_FACTORY_release_set_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0), C.swig_type_18(_swig_i_1))
}

func (arg1 SwigcptrH264_ENCODER_FACTORY) GetRelease() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_H264_ENCODER_FACTORY_release_get_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewH264_ENCODER_FACTORY() (_swig_ret H264_ENCODER_FACTORY) {
	var swig_r H264_ENCODER_FACTORY
	swig_r = (H264_ENCODER_FACTORY)(SwigcptrH264_ENCODER_FACTORY(C._wrap_new_H264_ENCODER_FACTORY_libvideo_e6881c35160e2f8e()))
	return swig_r
}

func DeleteH264_ENCODER_FACTORY(arg1 H264_ENCODER_FACTORY) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_H264_ENCODER_FACTORY_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

type H264_ENCODER_FACTORY interface {
	Swigcptr() uintptr
	SwigIsH264_ENCODER_FACTORY()
	SetId(arg2 Enum_SS___H264_ENCODER_ID)
	GetId() (_swig_ret Enum_SS___H264_ENCODER_ID)
	SetInit(arg2 _swig_fnptr)
	GetInit() (_swig_ret _swig_fnptr)
	SetRelease(arg2 _swig_fnptr)
	GetRelease() (_swig_ret _swig_fnptr)
}

func H264_encoder_init() {
	C._wrap_h264_encoder_init_libvideo_e6881c35160e2f8e()
}

func H264_encoder_register(arg1 H264_ENCODER_FACTORY) (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_h264_encoder_register_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Alloc_encoder_by_id(arg1 Enum_SS___H264_ENCODER_ID, arg2 ENCODE_PARAMETER) (_swig_ret X__H264_ENCODER_TH) {
	var swig_r X__H264_ENCODER_TH
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (X__H264_ENCODER_TH)(SwigcptrX__H264_ENCODER_TH(C._wrap_alloc_encoder_by_id_libvideo_e6881c35160e2f8e(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Free_encoder(arg1 X__H264_ENCODER_TH) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_free_encoder_libvideo_e6881c35160e2f8e(C.uintptr_t(_swig_i_0))
}

func Ffm_decoder_init() {
	C._wrap_ffm_decoder_init_libvideo_e6881c35160e2f8e()
}


type SwigcptrUint16_t uintptr
type Uint16_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint16_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_SwsContext uintptr
type Struct_SS_SwsContext interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_SwsContext) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrInt32_t uintptr
type Int32_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrInt32_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint32_t uintptr
type Uint32_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint32_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint8_t uintptr
type Uint8_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint8_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrLIBV_LOG_LEVEL_E uintptr
type LIBV_LOG_LEVEL_E interface {
	Swigcptr() uintptr;
}
func (p SwigcptrLIBV_LOG_LEVEL_E) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrLIBV_LOG_FUN uintptr
type LIBV_LOG_FUN interface {
	Swigcptr() uintptr;
}
func (p SwigcptrLIBV_LOG_FUN) Swigcptr() uintptr {
	return uintptr(p)
}

